cmake_minimum_required(VERSION 3.24)
project(geonames)

option(GEONAMES_CLI "Build the GeoNames CLI" OFF)

add_library(geonames src/geonames.cpp lib/sqlite3/sqlite3.c)
add_library(geonames::geonames ALIAS geonames)
target_include_directories(geonames PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)
target_include_directories(geonames PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/lib/sqlite3)
target_compile_definitions(geonames PRIVATE SQLITE_ENABLE_FTS5 SQLITE_ENABLE_DESERIALIZE)
set_target_properties(geonames PROPERTIES CXX_STANDARD 23)

if(GEONAMES_CLI)
    set(BINARY_DIR ${CMAKE_BINARY_DIR}/bin)
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${BINARY_DIR})
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${BINARY_DIR})
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG ${BINARY_DIR})
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${BINARY_DIR})
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE ${BINARY_DIR})
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG ${BINARY_DIR})
    make_directory(${BINARY_DIR})
    add_executable(cli src/cli.cpp)
    target_link_libraries(cli geonames)
    set_target_properties(cli PROPERTIES OUTPUT_NAME geonames)
    set_target_properties(cli PROPERTIES CXX_STANDARD 23)
endif()
